version: '3'
services:
  # OpenSearch
  opensearch:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: opensearch
    volumes:
      - /var/opensearch/data:/var/opensearch/data
      - os-data:/usr/share/opensaearch/data
    environment:
      - node.name=os-node
      - cluster.initial_master_nodes=os-node
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - http.host=0.0.0.0
      - transport.host=127.0.0.1
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - path.repo="/var/opensearch/data"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    networks:
      - osnet

  # OpenSearch Dashboards
  dashboard:
    build:
      context: .
      dockerfile: DockerfileDashboard
    container_name: opensearch-dashboard
    environment:
      OPENSEARCH_HOSTS: "https://opensearch:9200"
      OPENSEARCH_SSL_VERIFICATIONMODE: certificate
      OPENSEARCH_SSL_CERTIFICATEAUTHORITIES: "/usr/share/opensearch-dashboards/config/root-ca.pem"
    ports:
      - 5601:5601
    networks:
      - osnet

volumes:
  os-data:
    driver: local

networks:
  osnet:
