version: '3'
services:
  jupyter:
    build: .
    container_name: jupyterlab
    ports:
     - "10000:8888"
    volumes:
     - .:/home/jovyan/work
    environment:
      - JUPYTER_ENABLE_LAB=yes
    #command: jupyter/scipy-notebook
