version: '3'
services:
  web:
    build: .
    container_name: tlsserver
    ports:
     - "5000:5000"
    volumes:
     - .:/code
    tty: true
  client:
    image: centos:latest
    container_name: tlsclient
    tty: true

