version: '3'
services:
  web:
    build: .
    container_name: tlsserver
    ports:
     - "5000:5000"
    volumes:
     - .:/code
    tty: true
    command: /bin/bash
  client:
    # image: centos:latest
    build:
      context: .
      dockerfile: Dockerfile_client
    container_name: tlsclient
    tty: true

